steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build' 
      - '-t' 
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/mlflow-server:${_IMAGE_TAG}'
      - '.'
  
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push' 
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/mlflow-server:${_IMAGE_TAG}'

substitutions:
  _REGION: 'us-central1'
  _REPO_NAME: 'mlops-repo'
  _IMAGE_TAG: 'latest'

images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/mlflow-server:${_IMAGE_TAG}'