steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/mlflow-server:${_IMAGE_TAG}'
      - '.'
    id: 'build-image'

  # Step 2: Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/mlflow-server:${_IMAGE_TAG}'
    id: 'push-image'
    waitFor: ['build-image']

  # Step 3: Verify image was pushed successfully (opcional, para debugging)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'container'
      - 'images'
      - 'describe'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/mlflow-server:${_IMAGE_TAG}'
      - '--format=json'
    id: 'verify-image'
    waitFor: ['push-image']

substitutions:
  _REGION: 'us-central1'
  _REPO_NAME: 'mlops-repo'
  _IMAGE_TAG: 'latest'

images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/mlflow-server:${_IMAGE_TAG}'

# Configuraci칩n adicional
timeout: '600s'  # 10 minutos timeout
options:
  machineType: 'E2_HIGHCPU_8'  # M치quina m치s potente para builds r치pidos
  diskSizeGb: '100'
  logging: CLOUD_LOGGING_ONLY